### ISSUE TITLE
DRM Key request 

### ISSUE THREAD

**Issue by KarelPuhli** [Jey-Cee/ioBroker.upnp#100]
Hallo!
I installed the upnp adapter and discovered some states named >>DRMType<<. Is there a possibility to get the DRM Key of my Samsung Smart TV without rooting the TV? The TV is in the object list. I need the key for encrypting the recorded videos via USB. 
Thanks for your answer!
PS: Its a Samsung Smart TV of the F series.

**Comment by Jey-Cee** [comment]
Hey, 
i dont think it is possible to retrive a DRM Key via upnp.
