### ISSUE TITLE
Warn message: Object of state "upnp.0.*****" is missing the required property "common.type"

### ISSUE THREAD

**Issue by MSal-RPI4** [Jey-Cee/ioBroker.upnp#101]
### Contact Details

mssalmang@gmail.com

### What happened?

Script "setState( "upnp.0.xxxx",'yyyy')" works just fine except a.m. WARN message, unnecessarily filling up the log.

### Adapter Version

1.0.19

### JS-Controller Version

3.3.15

### Node JS Version

14.18.3

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Please check version 1.3.20
