### ISSUE TITLE
[Feature]: Weitere Services der FritzBox implementieren https://avm.de/service/schnittstellen/

### ISSUE THREAD

**Issue by ckoeber83** [Jey-Cee/ioBroker.upnp#176]
Hi Jey-Cee,

ist es möglich weitere Services der FritzBox  zu implementieren, außer der WANCommonInterfaceConfig?

Ich habe in meinem IOBroker nur diese
![grafik](https://github.com/Jey-Cee/ioBroker.upnp/assets/52466072/dec5fdbf-ad4c-4c4e-b81c-5c574dad0b92)
und WANConnectionDevice
![grafik](https://github.com/Jey-Cee/ioBroker.upnp/assets/52466072/8687796c-ea4d-407e-9ab2-2f89238197b7)

Es gibt aber laut [AVM Entwicklungssupport](https://avm.de/service/schnittstellen/) noch mehr Schnittstellen wie:
- [X_AVM-DE_WANMobileConnection](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_wanmobileconnSCPD.pdf)
- Telefonie
- Heimnetz
- Speicher/NAS
- System
und und und, siehe > https://avm.de/service/schnittstellen/

Lassen sich diese auch in dem upnp Adapter integrieren, um Werte im IOBroker zu erhalten.

Danke und viele Grüße

**Comment by Jey-Cee** [comment]
Der upnp Adapter implementiert das Gleichnahmige Protokoll, das ist generisch und wenn AVM die Funktionen nicht über das Protokoll preisgibt kann er das nicht abbilden. 

Für Fritzboxen gibt es den TR064 Adapter, da wäre dein Request für Zusätzliche Funktionen besser Aufgehoben.
