### ISSUE TITLE
Make sure object/state IDs do not contain *, ? [ or ] or " or '

### ISSUE THREAD

**Issue by Apollon77** [Jey-Cee/ioBroker.upnp#18]
... to stay compatible with js-controller 1.4x+

see also https://github.com/ioBroker/ioBroker.js-controller/issues/198

**Comment by Apollon77** [comment]
Best would be to just replace not allowed characters with underscore or such then restoring history logging via script would be very easy.

**Comment by Jey-Cee** [comment]
Done

**Comment by Apollon77** [comment]
Thank you!
