### ISSUE TITLE
Auto discover: undefined

### ISSUE THREAD

**Issue by stavrostz** [Jey-Cee/ioBroker.upnp#9]
After installing the upnp adapter on a fresh iobroker installation, i get the following messages in the log and no devices will be finding:

upnp.0	2017-03-03 04:16:38.762	info	Auto discover: undefined
upnp.0	2017-03-03 04:16:38.740	info	starting. Version 0.3.5 in /opt/iobroker/node_modules/iobroker.upnp, node: v6.10.0
host.	2017-03-03 04:16:38.589	info	States connected to redis 127.0.0.1:6379
host.ioBroker-BPi	2017-03-03 04:16:31.703	info	instance system.adapter.upnp.0 started with pid 2461
host.ioBroker-BPi	2017-03-03 04:16:29.265	info	instance system.adapter.upnp.0 terminated with code 0 (OK)

**Comment by jens-maus** [comment]
Just want to state that I am getting the same output here with "Auto discover: undefined". Thus the auto discover doesn't seem to start at all with that setting not being available.

**Comment by Jey-Cee** [comment]
I hope its fixed now. Please install from Github to test and let me know if it is ok now.

**Comment by stavrostz** [comment]
it works now. thank you
